### ISSUE TITLE
Проверить расчет вместимости на катушках в Expert V

### ISSUE THREAD

**Issue by Shtirlits57rus** [AB-TREYD/1C#48]
Ссылка на разбивку: e1cib/data/Справочник.РазбивкаЗаказа?ref=aad1f8f21ea656f911ef86fc26463525
В этом заказе надо проверить при расчете вместимостей катушек на 3 этапе (скрутка стренги) определяется вместимость катушки по массе, исходя из ограничения внутри справочника, однако согласно комментарию от Лалакиной, подтягивается не 150 кг, а 305, необходимо проверить это.

Ссылка на разбивку: e1cib/data/Справочник.РазбивкаЗаказа?ref=9f24f8f21ea98a9911ef6607ed2717b2
Expert V разбил на три куска, Лалакина на 2, выяснить у неё как так вышло и почему, сравнить с нашим алгоритмом

**Comment by nikmik101** [comment]
Закрыто
