### ISSUE TITLE
Очередь заказов на производство необходимо оптимизировать

### ISSUE THREAD

**Issue by Shtirlits57rus** [AB-TREYD/1C#57]
Слишком долгое выполнение процессов после каждого действия/движения на форме списка после того, как мы её переделали в табличную засть

**Comment by holphi-01** [comment]
Реализовано с помощью замены **_ОбновитьИнтерфейс_** в форме документа **_Сгруп заказа_** на **_Оповещение_**

![Image](https://github.com/user-attachments/assets/9fcc1e0c-5aa3-4ac4-8f81-7015e7d21b78)
