### ISSUE TITLE
Разобраться с номерами приоритетов заказов

### ISSUE THREAD

**Issue by Shtirlits57rus** [AB-TREYD/1C#63]
Так как плановики не двигают заказы, требуется пробовать самостоятельно перемещать заказы и мониторить, как меняются номера приоритетов. Проверить что происходит с новыми заказами. Нажимать на кнопку сортировки номеров приоритета (чтобы начать нумерацию с первой позиции. По умолчанию все новые позиции в Expert V изначально должны были заводиться под номером 1000 и выше

**Comment by nikmik101** [comment]
Были проверены 2 кнопки "Перенумеровать приоритет" и "Обнулить приоритет завершённых заказов", обе работают исправно.
