### ISSUE TITLE
Добавить формулы для расчета Милликена

### ISSUE THREAD

**Issue by Shtirlits57rus** [AB-TREYD/1C#77]
- [x] e1cib/data/Документ.ЗаказыВПроизводство?ref=aad5f8f21ea656f911ef9910f4495460
- [x] Добавить в формулы расчет для Милликена, Основная жила переименовывается синоним в Центральная жила, а Плюсовая - в Сектор. Центральная мк, Сектор - мс
- [ ] Добавить новый вид операции СборкаЖилыМилликен, детали уточнить позже, пока заглушкой
Пароль к файлу для формул 555

**Comment by nikmik101** [comment]
> [!WARNING]
>  Пролистал интернет, но так и не нашёл, чтобы у перечисления можно было изменить синоним.

Альтернативный вариант, можно:
1. добавить новые значения перечисления.
2.  Добавить реквизит формы, которые будет отражать синоним перечисления и если что менять его.

**Comment by nikmik101** [comment]
<details><summary>Details</summary>
<p>

Из-за того что у нас у секторной жилы нету диаметра ТПЖ, нужно продумать, как тогда находить конечный диаметр, просто брать высоту сегмента? И в целом нужно обсудить, как буду считаться НормаНа1КМ и Потребность
![Image](https://github.com/user-attachments/assets/598eb315-9265-45e8-bfe3-cb9a9aace0b1)


</p>
</details>
