### ISSUE TITLE
Добавление расчёта коэффициента в формулу нормы на волочении

### ISSUE THREAD

**Issue by nikmik101** [AB-TREYD/1C#85]
### Задача: Добавить расчёт коэффициента укрути.
Сейчас коэффициент просто заносится программно в функции ЗаполнитьПРПВолочение(), занесение представлено на рисунке ниже.
![image](https://github.com/user-attachments/assets/55bd88fa-a02e-45dd-b745-eedf8aab3a32)
рис. 1. Внесение коэффициента
Нужно сделать, чтобы коэффициент рассчитывался в функции ВолочениеБазовая() и возможно в ВолочениеШахтный().
Объединить 2 формулы, чтобы например если требуется расчёт для круглой жилы, то просто шаг скрутки заполнялся нулём в ВолочениеБазовая().
![ФОрмулаЖилы](https://github.com/user-attachments/assets/86e80457-fe9c-43fb-a48f-e97a0207532e)
рис. 2. Формула расчёта коэффициента

Сам коэффициент используется в формуле расчёты нормы на км.
![image](https://github.com/user-attachments/assets/4e88a859-0e26-4cc5-b6d0-2ef37daf237e)
рис. 3. Использование коэффициента

**Comment by nikmik101** [comment]
Также прикладываю весь файл с формулами, где можно посмотреть приложения.
[Методика_расчета_Кабели_никого_напряжения.docx](https://github.com/user-attachments/files/18033832/_._._._.docx)

**Comment by holphi-01** [comment]
Коэф. рассчитывается по одинаковой формуле, так же как и для изоляции. Проблемы такие же, см. https://github.com/orgs/AB-TREYD/projects/4/views/1?pane=issue&itemId=89949687&issue=AB-TREYD%7C1C%7C87

**Comment by Shtirlits57rus** [comment]
Нет никакой проблемы, в этом и смысл задачи, чтобы вынести расчет коэффициента в отдельную функцию и передавать туда нужный параметр, в зависимости от того, из какой процедуры он вызывается

**Comment by holphi-01** [comment]
Функция поиска одинаковая 

Комментарии удалены, скрин для наглядности изменений в функции **ЗаполнитьПРПВолочение**
Перенесено на хранилище

![Image](https://github.com/user-attachments/assets/364bbff8-f049-4670-9fd6-a96c02b10a2b)
