### ISSUE TITLE
Нахождение диаметра для плюсового кабеля на общей скрутки

### ISSUE THREAD

**Issue by nikmik101** [AB-TREYD/1C#86]
Добавить нахождение диаметра для **плюсового** кабеля в функции ОбщаяСкруткаБазовая().
![image](https://github.com/user-attachments/assets/7f322d25-6dc6-4dbf-b887-30a54264f4f2)

Формула для нахождения диаметра представлена ниже.
![image](https://github.com/user-attachments/assets/0240dd5d-348c-40a5-bdfe-2955bbe34cb0)

**Comment by nikmik101** [comment]
Видимо это уже сделано, я по коду на нашёл, чтобы это делалось, но Воронин говорит, что всё так. ПРОВЕРИТЬ!!!

**Comment by holphi-01** [comment]
Добавляем в **ЗаполнитьПРПОбщаяСкрутка**
![Image](https://github.com/user-attachments/assets/dbf7bb46-0e3d-4f56-920d-0180c7bd2b50)

---
Почти одно и тоже
![Image](https://github.com/user-attachments/assets/83f63a1d-5a38-4ab6-ac64-42252f758958)

**Comment by holphi-01** [comment]
Перенесено в хранилище
