### ISSUE TITLE
Добавление расчёта коэффициента на изоляции

### ISSUE THREAD

**Issue by nikmik101** [AB-TREYD/1C#87]
Сейчас коэффициент подтягивается из справочника ЗначениеКоэффициентаУкрутки.
![image](https://github.com/user-attachments/assets/72435518-a930-4133-ac58-36148b7e6e49)
Нужно добавить расчёт коэффициента укрути изолированной жилы в функцию ИзоляцияБазовая(), формула представлена на рисунке ниже 
![image](https://github.com/user-attachments/assets/62044593-3ca7-4451-b872-938a99146adc)
Сам коэффициента используется в формуле расчета потребности
![image](https://github.com/user-attachments/assets/6c90599c-a65a-45ea-a3f7-9c20d21e4a8d)

**Comment by nikmik101** [comment]
Также прикладываю весь файл с формулами, где можно посмотреть приложения.
[Методика_расчета_Кабели_никого_напряжения.docx](https://github.com/user-attachments/files/18033840/_._._._.docx)

**Comment by holphi-01** [comment]
Промежуточное решение. Возможно неправильное
---

    Функция Изоляция_КоэфУкруткиЖил(СПЗ)          
	    Сектор  = Нрег(Строка(СПЗ.ИсполнениеЖилы)) = "мс";
	    Круглый = Не СПЗ.Плоский;    
	    Кукр = 1;         
	    
	    ДиамПоСкрутке = СПЗ.ТЗДанныеПоЭтапам[СПЗ.ИндексНомераЭтапа-1].ДиамКон;	   
	    Если Круглый тогда     
		    КратностьШагаСкрутки = Изоляция_ПолучитьЗначениеИзКратностьШагаСкрутки(СПЗ);     // 1.2-1.4 
		    
		    Кукр = Pow(	Pow(пи()*ДиамПоСкрутке,2)+Pow(КратностьШагаСкрутки*ДиамПоСкрутке,2),0.5)/(ДиамПоСкрутке*КратностьШагаСкрутки);
	    ИначеЕсли Сектор тогда //Сектор    
		    //по ТЗ для этой ветки используется табл 1.1 и 1.5, 1.5 табл для Сипа. Сип не сектор, сюда не попадает и формулу не использует.
		    ШагСкрутки = Изоляция_ПолучитьЗначениеИзШагСкруткиСекторнойЖилы(СПЗ);     //1.1	
		    
		    Кукр = Pow(	Pow(пи()*ДиамПоСкрутке,2)+Pow(ШагСкрутки,2),0.5)/(ШагСкрутки);		
	    КонецЕсли;
	    Возврат Кукр;
    КонецФункции
---
    Функция Изоляция_ПолучитьЗначениеИзШагСкруткиСекторнойЖилы(СПЗ)
	    ЗначСправочника = Неопределено;
	    Запрос = Новый Запрос;
	    Запрос.Текст = 
	    "ВЫБРАТЬ Первые 1
	    |	ШагСкруткиСекторнойЖилы.ШагСкрутки КАК ШагСкрутки
	    |ИЗ
	    |	Справочник.ШагСкруткиСекторнойЖилы КАК ШагСкруткиСекторнойЖилы
	    |ГДЕ
	    |	ШагСкруткиСекторнойЖилы.КоличествоЖил = &КоличествоЖил
	    |	И ШагСкруткиСекторнойЖилы.Сечение = &Сечение";
	    
	    Запрос.УстановитьПараметр("КоличествоЖил",  СПЗ.КоличествоЖил); //тут надо ссылку
	    Запрос.УстановитьПараметр("Сечение", 		СПЗ.Сечение);             //тут надо ссылку
	    
	    РезультатЗапроса = Запрос.Выполнить();
	    ВДЗ = РезультатЗапроса.Выбрать();
	    
	    Пока ВДЗ.Следующий() Цикл
		    ЗначСправочника = ВДЗ.ШагСкрутки;
	    КонецЦикла;
	    Возврат ЗначСправочника
    КонецФункции
---
    Функция Изоляция_ПолучитьЗначениеИзКратностьШагаСкрутки(СПЗ)
	    Если СПЗ.ТипКабеля=Перечисления.ТипПродукции.КабельКонтрольный тогда      //3. Контрольные 
		    КлассЖилы = Перечисления.ТипПродукции.КабельКонтрольный;
	    ИначеЕсли СПЗ.Гибкий тогда  
		    КлассЖилы = Перечисления.ТипПродукции.Жилы5класса; //4. ГибкаяЖила 		
	    Иначе КлассЖилы = Перечисления.ТипПродукции.Жилы2класса;	
	    КонецЕсли;
	    
	    КратностьШагаСкрутки = неопределено;
	    
	    Запрос = Новый Запрос;
	    Запрос.Текст = 
		    "ВЫБРАТЬ Первые 1
		    |	КратностьШагаСкрутки.Кратность КАК Кратность
		    |ИЗ
		    |	Справочник.КратностьШагаСкрутки КАК КратностьШагаСкрутки
		    |ГДЕ
		    |	КратностьШагаСкрутки.ТипКабеля = &КлассЖилы";
	    
	    Запрос.УстановитьПараметр("КлассЖилы", КлассЖилы);
	    
	    РезультатЗапроса = Запрос.Выполнить();
	    
	    ВДЗ = РезультатЗапроса.Выбрать();
	    
	    Пока ВДЗ.Следующий() Цикл
		    КратностьШагаСкрутки = ВДЗ.Кратность;	
	    КонецЦикла;
	    
	    Возврат КратностьШагаСкрутки;
    КонецФункции

**Comment by holphi-01** [comment]
Поговорив с Ворониным выяснилось, что Дск это диаметр по скрутке, он вычисляется на этапе скрутки. На этапе изоляции у нас нет данных по диаметру скрутки, т.к. скрутки еще не произошло. Возможно следует на общей скрутке возвращаться в расчет изоляции и добавлять туда коэффициент...

**Comment by Shtirlits57rus** [comment]
Дск (исходя из п.2-3 из файла) есть умножение коэффициента скрутки на диаметр изолированной жилы. Диаметр изолированной жилы на изоляции у нас вычисляется, коэффициент берется из таблицы. То есть надо просто добавить функцию расчета Dск. Причем, судя по методичке, эта функция будет вызываться из нескольких мест. Учитывая, что Dск не влияет на полученную цифру, нам в данном случае вообще не важно, что мы получаем)

Вот это не будет работать: 

"Сектор  = Нрег(Строка(СПЗ.ИсполнениеЖилы)) = "мс";
 Круглый = Не СПЗ.Плоский;    
 Кукр = 1;
 Если Круглый тогда     
 	 ...
 ИначеЕсли Сектор тогда //Сектор "

Формула там одна, просто для  (Zиз*Dск+Hиз)^2 в числителе, а в знаменателе (Zиз*Dск+Hиз). Соответственно, если сектор, то  Zиз = 0, если круглый, то  Hиз = 0

**Comment by holphi-01** [comment]
Функция **ЗаполнитьПРПИзоляция**
залито на хранилище. на первой картинке изменения в коде, на 2 и 3 добавления функций

![Image](https://github.com/user-attachments/assets/14156720-9176-4b73-bd72-a8916082d854)

![Image](https://github.com/user-attachments/assets/3aaa925e-1d87-4d3b-89f4-cc1a1a5ff135)
![Image](https://github.com/user-attachments/assets/77e48236-2e70-4ff7-a19b-288d9888b387)
